- name: correct node kubeconfig
  lineinfile:
    path: /etc/origin/node/node.kubeconfig
    regexp: '^current-context: '
    line: "current-context: default/{{currentContext}}:8443/system:admin"
    backup: yes

- name: correct bootstrap node kubeconfig
  lineinfile:
    path: /etc/origin/node/bootstrap.kubeconfig
    regexp: '^current-context: '
    line: "current-context: default/{{currentContext}}:8443/system:admin"
    backup: yes

- name: correct master kubeconfig
  lineinfile:
    path: /etc/origin/master/admin.kubeconfig
    regexp: '^current-context: '
    line: "current-context: default/{{currentContext}}:8443/system:admin"
    backup: yes
  when: "'masters' in group_names"
