- name: correct node kubeconfig current context
  lineinfile:
    path: /etc/origin/node/node.kubeconfig
    regexp: '^current-context: '
    line: "current-context: default/{{currentContext}}:{{apiPort}}/system:admin"
    backup: yes
  when: "'masters' in group_names"

- name: correct node kubeconfig server value
  lineinfile:
    path: /etc/origin/node/node.kubeconfig
    regexp: '    server: '
    line: "    server: https://{{openshift_master_cluster_hostname}}:{{apiPort}}"
    backup: yes
  when: "'masters' in group_names"

- name: correct bootstrap node kubeconfig current context under node dir
  lineinfile:
    path: /etc/origin/node/bootstrap.kubeconfig
    regexp: '^current-context: '
    line: "current-context: default/{{currentContext}}:{{apiPort}}/system:admin"
    backup: yes
  when: "'masters' in group_names"

- name: retrieve bootstrap file from master node dir
  fetch:
    src: /etc/origin/node/bootstrap.kubeconfig
    dest: ../bootstrap.kubeconfig
    flat: yes
  when: "'masters' in group_names"

- name: copy bootstrap file to nodes
  copy:
    src: ../bootstrap.kubeconfig
    dest: /etc/origin/node/
    backup: yes
  when: "'masters' not in group_names"

- name: retrieve node kubeconfig file from master
  fetch:
    src: /etc/origin/node/node.kubeconfig
    dest: ../node.kubeconfig
    flat: yes
  when: "'masters' in group_names"

- name: copy node kubeconfig file to nodes
  copy:
    src: ../node.kubeconfig
    dest: /etc/origin/node/
    backup: yes
  when: "'masters' not in group_names"

- name: correct master kubeconfig
  lineinfile:
    path: /etc/origin/master/admin.kubeconfig
    regexp: '^current-context: '
    line: "current-context: default/{{currentContext}}:{{apiPort}}/system:admin"
    backup: yes
  when: "'masters' in group_names"

- name: correct node kubeconfig current context
  lineinfile:
    path: /root/.kube/config
    regexp: '^current-context: '
    line: "current-context: default/{{currentContext}}:{{apiPort}}/system:admin"
    backup: yes
  when: "'masters' in group_names"

