---


- hosts: nodes
  gather_facts: false
  serial: "100%"


  roles:
    - fixConfigs


- hosts: localhost
  gather_facts: false

  tasks:


  - name: copy kubeconfig
    fetch:
      src: /root/.kube/config
      dest: ../kubeconfig
      flat: yes
    delegate_to: "{{groups['masters'] | first}}"


- hosts: nodes
  gather_facts: false
  serial: 1
  roles:
    - restart_nodes 

- hosts: nodes
  gather_facts: false
  serial: "100%"
  roles:
    - generate_new_bootstrap

- hosts: localhost
  gather_facts: false


  tasks:


  - name: Final Check | pause for 5 minutes
    pause:
      minutes: 5

  - name: Final Check | Check that all pods returned after tests
    shell: "oc --config=../kubeconfig get pods --all-namespaces|grep -v Running|grep -v Completed|grep -v NAMESPACE|grep -v NAME|grep -v READY| grep -v STATUS| grep -v RESTARTS| grep -v AGE"
    changed_when: 1==2
    register: finalstatus
    failed_when: finalstatus.stdout != ""
